# GLOBAL CONFIGURATION
spring:
  application:
    name: cs-assignment
  jpa:
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:/liquibase/changelog.xml
    enabled: true
  config:
    import: vault://
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      uri: http://localhost:8200
      connection-timeout: 5000
      read-timeout: 15000

server:
  port: 8080



logging:
  level:
    org:
      springframework:
        cloud:
          vault: trace
        vault: debug